management:
  health:
    redis:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  cloud:
    compatibility-verifier:
      enabled: false # 禁用版本兼容性校验
    autoconfigure:
      exclude: com.alibaba.druid.spring.boot3.autoconfigure.stat.DruidStatViewServletConfiguration
  #  cloud:
  #    nacos:
  #      discovery:
  #        server-addr: nacos:8848
  #  data:
  #    redis:
  #      repositories:
  #        #forbid redis to scan repositories
  #        enabled: false
  #   #redis:
  #      host: redis
  #      database: 0
  #      password: 123456
  datasource:
    #JDBC drivers
    driver-class-name: com.mysql.cj.jdbc.Driver
    #database url
    url: jdbc:mysql://localhost:3306
    #database username and password
    username: root
    password: Ooad_2_8
    #database connection pool
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 3
      min-idle: 3
      max-active: 100
      max-wait: 60000
      stat-view-servlet:
        login-username: admin
        login-password: 123456
        enabled: true
        url-pattern: /druid/*
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 100
      validation-query: select 1
  jackson:
    time-zone: GMT+8
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: false

server:
  port: 8081
  tomcat:
    threads:
      max: 100
      min-spare: 3

oomall:
  core:
    page-size:
      max: 1000
      default: 10
  region:
    timeout: 3600

logging:
  level:
    cn.edu.xmu.javaee.core: debug
    cn.edu.xmu.oomall.service: debug

